### ISSUE TITLE
Duplicate (v2.3.3) - BubbleCard is responsible for high delays in FullyKiosk

### ISSUE THREAD

**Issue by Schwippser** [Clooos/Bubble-Card#1048] opened 2024-12-13 18:55 UTC
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
Since updating to v2.3.3, extreme delays have been observed in Fullykiosk

**To Reproduce**  
1. update custom:bubble-card to v2.3.3
2. reload Homeassistant
3. compare time in Chrome with time in FullyKiosk
4. delay of about 25 seconds

Thank you! 🍻

**Comment by MrBearPresident** [comment] 2024-12-13 19:41
@Schwippser please revert back to 2.3.0
All latest releases are labeled as pre-release.

**Comment by MrBearPresident** [comment] 2024-12-13 19:42
Duplicate of #1035

**Closed** 2024-12-13 19:42 UTC
Labels: bug, duplicate
