### ISSUE TITLE
After Update Rows are false

### ISSUE THREAD

**Issue by mrfrag1** [Clooos/Bubble-Card#335] opened 2024-01-06 18:08 UTC
After the update, my two grids are no longer displayed next to each other but one below the other.

If I uninstall Bubble Card it works again.

Since V1.6x

So ok:
<img width="774" alt="dual" src="https://github.com/Clooos/Bubble-Card/assets/108211193/48d9df14-d3b9-464d-bb22-92f03e69ff3e">

So not Ok:
<img width="1360" alt="one" src="https://github.com/Clooos/Bubble-Card/assets/108211193/1aaa00d9-6030-4d51-b0c0-2cd0f679a73f">

**Comment by mrfrag1** [comment] 2024-01-06 18:11
<img width="159" alt="unter" src="https://github.com/Clooos/Bubble-Card/assets/108211193/f9e11d6d-de38-4c09-807e-bd9b54273060">

**Comment by Clooos** [comment] 2024-01-06 19:06
Hi, this issue is a duplicate of this one:
https://github.com/Clooos/Bubble-Card/issues/336

**Closed by Clooos** 2024-01-06 19:06 UTC
