### ISSUE TITLE
Volume slider (Media Player card) close button not behaving as expected.

### ISSUE THREAD

**Issue by alirankine** [Clooos/Bubble-Card#994] opened 2024-12-04 18:30 UTC
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
HIGH LEVEL: Close button for volume slider in Media Card not behaving as expected.

I have created a Media Player card type, and enabled the volume button.
When I click the volume button, the popup volume slider appears and I can adjust the volume, but when I close the volume slider, I can no longer see the Artist and Song Name, also the 'Close' icon remains in place (rather than the volume icon). I need to refresh the page in order for the Artist and Song to re-appear and for the close button to revert back to the volume button.

**To Reproduce**  
1. Click the volume button in the Media Player card.
2. Click the close button in the Media Player card.
3. Error above becomes present.

**Expected behavior**  
The volume slider should close, the Arist and Song name should re-appear and the close button should revert back to the volume button.

**Screenshots**  
<img width="417" alt="image" src="https://github.com/user-attachments/assets/d040bd46-e7f6-4417-a9f1-4094aa357f8b">
<img width="395" alt="image" src="https://github.com/user-attachments/assets/060f0362-18e9-48a4-812e-5b473286b99d">
<img width="408" alt="image" src="https://github.com/user-attachments/assets/e6e347fd-d644-462e-8348-32eea88fc85e">

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: custom:bubble-card
card_type: media-player
name: Media player
entity: media_player.dining_room
show_state: false
show_last_updated: true
show_attribute: false
attribute: assumed_state
card_layout: large
scrolling_effect: true
show_icon: true
force_icon: false
show_name: false
show_last_changed: false
columns: 4
rows: 1
hide:
  power_button: true
cover_background: true
```

**Informations (please complete the following information):**  
 - OS: Windows 11
 - Browser/App: Chrome
 - Bubble Card version: 2.3.0
 - Home Assistant version: Core: 2024.11.3 Supervisor: 2024.11.4 (Running on RPi4 HAOS)

**Additional context**  

Thank you! 🍻

**Comment by returnofthem** [comment] 2024-12-06 09:22
Confirming I see this behaviour as well.

**Comment by MrBearPresident** [comment] 2024-12-06 14:11
Confirming this behaviour on my daily driver but not on my test-docker

**Comment by MrBearPresident** [comment] 2024-12-06 14:37
Temporary FIX:
Add this to your yaml of the button:
`sub_button: []`

**Comment by MrBearPresident** [comment] 2024-12-06 17:33
#1001 

Made a PR

**Comment by returnofthem** [comment] 2024-12-06 19:09
> Temporary FIX: Add this to your yaml of the button: `sub_button: []`

This works for me, thank you!

**Comment by MrBearPresident** [comment] 2024-12-06 22:40
Will be in next release. 
@Clooos You can close this.

**Comment by Clooos** [comment] 2024-12-12 12:57
The new release is here! Tell me if everything works as it should now 🙂 

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.1

And thank you again @MrBearPresident for this!

**Comment by returnofthem** [comment] 2024-12-12 19:02
Confirmed that fixes it for me after removing the workaround - thank you!

**Closed** 2024-12-12 19:11 UTC
Labels: bug
