### ISSUE TITLE
Separator sub-buttons cause haptic feedback loop on tap and never open "more-info". 

### ISSUE THREAD

**Issue by aredon** [Clooos/Bubble-Card#601] opened 2024-06-25 20:09 UTC
**Describe the bug**  
When tapping on a sensor entity in a separator card (not inside a popup) the haptic feedback on my phone begins to pulse rapidly. I assume some kind of loop is messed up here. More-info does not open and the app will sometimes freeze. What's odd is sometimes it will only pulse a few times and then work normally. 

**To Reproduce**  
1. Create a separator with a sub button sensor entity
2. Tap it
3. Panic while your phone freaks out

**Expected behavior**  
More info dialog 

**Screenshots**  
N/A

**Informations (please complete the following information):**  
 - OS: Android 11
 - Browser: HA App
 - Bubble Card version: 2.0.4
 - Home Assistant version: 2024.6.4

**Comment by Clooos** [comment] 2024-06-25 20:33
Thank you for the feedback! 

I did realized that but I was not able to find how to reproduce it, I will take a look at that!

**Comment by Clooos** [comment] 2024-06-25 20:36
Damn I've just tried and I'm still unable to reproduce this issue.

**Comment by aredon** [comment] 2024-06-25 21:44
So I'm wondering if it has to do with load/response times from home assistant. I can't get it to happen consistently but I have more luck when I'm on phone data rather than wifi.

Is the code for the haptic feedback basically loop until response received?

**Comment by Clooos** [comment] 2024-06-25 21:47
If I remember correctly no it's not, but this issue shouldn't be too difficult to fix, there is not too much code to check for that feature.

**Comment by aredon** [comment] 2024-06-25 23:09
I put my phone in airplane mode and it's still not doing it. So I'm starting to lean more toward cache issue - as in - first load of those entities.

**Comment by Clooos** [comment] 2024-07-06 22:02
This issue is now fixed in the news betas, it was part of a massive memory leak.

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.0-beta.2

**Closed by Clooos** 2024-07-06 22:02 UTC
Labels: bug
