### ISSUE TITLE
v2.3.0-beta.7 Temperature selector text not colored (maybe a bug?)

### ISSUE THREAD

**Issue by flz** [Clooos/Bubble-Card#941] opened 2024-11-19 03:22 UTC
**Describe the bug**  

Thermostat target temperatures are only colored when heat_cool mode is selected. When mode is set to heat or cool, the text remains white.

**Expected behavior**  

Expecting target low temperature to be orange and target high temperature to be blue regardless of mode.

**Screenshots**  

<img width="513" alt="Screenshot 2024-11-18 at 7 15 50 PM" src="https://github.com/user-attachments/assets/41c497ec-03de-4180-89c7-3a7417364cf5">

**Informations (please complete the following information):**  
 - OS: Mac OS
 - Browser/App: Chrome
 - Bubble Card version: v2.3.0-beta.7 
 - Home Assistant version: 2024.11.x

**Comment by flz** [comment] 2024-11-19 03:22
Thanks for your support! Apologies for adding yet another issue in your release backlog :-)

**Comment by Clooos** [comment] 2024-11-19 13:05
Hi! This is the expected behavior but I hesitate for that, since there is only one value displayed, it makes more sense when there are two values.

What do you think?

**Comment by Clooos** [comment] 2024-11-19 18:18
I still don't know, the issue is that in some entities I can't be sure of what type of device it is (AC or heater), so I can't define a color by default. But it is easy to modify it with just a single line in the custom styles section.

**Comment by flz** [comment] 2024-11-20 04:17
I've tried to change it using styles but haven't figured it out yet. If you can suggest how to do it, that would be great :-)

**Comment by Clooos** [comment] 2024-11-20 10:22
You can just add this for heater:

```yaml
.bubble-temperature-display {
  color: var(--state-climate-heat-color);
}
```

And this for AC:

.bubble-temperature-display {
  color: var(--state-climate-cool-color);
}

I will close this, but don't hesitate to ask if you have more questions 🙂

**Closed by Clooos** 2024-11-20 10:22 UTC
Labels: bug

**Comment by flz** [comment] 2024-11-20 18:52
Thanks, I'll just comment here what I ended up with since your snippet assumed different entities for heater and AC while I wanted the text color to change based on current mode:

```
.bubble-temperature-display {
  color: ${state === "heat" ? "var(--state-climate-heat-color)" : "var(--state-climate-cool-color)" }
}
```

Thanks for your help!

**Comment by Clooos** [comment] 2024-11-20 20:15
Even better, thanks for sharing this! 👌
