### ISSUE TITLE
2.3.0 - Gauge card missing text

### ISSUE THREAD

**Issue by liamstears** [Clooos/Bubble-Card#944] opened 2024-11-20 11:47 UTC
Since the 2.3.0 beta's any gauge card doesn't display text, 2.2.4 works fine 

I have attached 2 pictures, how it should look using 2.2.4 and how it looks with any 2.3.0 beta

![Screenshot_20241120_114322_Home Assistant](https://github.com/user-attachments/assets/e814ec7b-be35-4df1-9231-7a525968ac91)
![Screenshot_20241120_114244_Home Assistant](https://github.com/user-attachments/assets/aad2d6c5-2735-47da-966f-81a9cc730732)

**Comment by Clooos** [comment] 2024-11-20 11:50
Hi, can you provide more context? I guess that this in a pop-up context, can you provide this pop-up YAML?

**Comment by liamstears** [comment] 2024-11-20 11:53
> Hi, can you provide more context? I guess that this in a pop-up context, can you provide this pop-up YAML?

Yes it is, I have many popups, all different with different yaml yet the same behaviour for this gauge card

Here is the yaml for the gauge: 

`          - type: gauge
            entity: sensor.living_room_thermometer_humidity
            name: Humidity
            max: 100
            min: 0
            segments:
              - from: 0
                color: "#f70031"
              - from: 20
                color: "#ffa600"
              - from: 40
                color: "#008f12"
              - from: 60
                color: "#0e8bb4"
              - from: 80
                color: "#004fe0"
            needle: true
            card_mod:
              style:
                ha-gauge:
                  $: |
                    svg.text {
                      max-height: 35% !important;
                    }
                .: |
                  ha-card {
                    padding: 4px 16px 4px !important;
                    box-shadow: none !important;
                    border-style: none !important;
                    background: none !important;
                    font-color: red !important;
                  }
                  ha-gauge {
                    max-width: 128px !important;
                  }
                  .name {
                    font-size: 13px !important;
                    margin-top: 4px !important;
                    margin-bottom: 4px !important;
                  }
`

**Comment by Clooos** [comment] 2024-11-20 11:56
Just tried your YAML and I have no issue:

<img width="653" alt="image" src="https://github.com/user-attachments/assets/26c2b653-f383-4daf-a0af-e9bcfdacfa0b">

**Comment by Clooos** [comment] 2024-11-20 11:59
If you don't find the cause of this you can also try this:

https://github.com/Clooos/Bubble-Card/issues/399#issuecomment-1962839344

**Comment by liamstears** [comment] 2024-11-20 12:01
> If you don't find the cause of this you can also try this:
> 
> [#399 (comment)](https://github.com/Clooos/Bubble-Card/issues/399#issuecomment-1962839344)

It's certainly an odd one as 2.2.4 works fine, I'll have a play and change various yaml see if anything brings them back, thanks

**Comment by Clooos** [comment] 2024-11-20 12:13
Have you tried to clear the HA app cache?

**Comment by liamstears** [comment] 2024-11-20 12:26
> Have you tried to clear the HA app cache?

Ah, I've fixed it!

Previously had this issue and had to set background_update: true

Now however I've had to change all popup card to background_update: false

This seems to fix it

Strange?

**Comment by Clooos** [comment] 2024-11-20 20:14
Perfect then! Glad that you fixed it! And it's always better to have `background_update` disabled when possible, so it's all good 👌

I'm closing this 🎉

**Closed by Clooos** 2024-11-20 20:14 UTC
Labels: bug
