### ISSUE TITLE
duplicate [v2.3.1-2.3.3] Problems

### ISSUE THREAD

**Issue by KLST2603** [Clooos/Bubble-Card#1046] opened 2024-12-13 17:53 UTC
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**YAML**  
If applicable, add any relevant YAML code.

```yaml
Your code here
```

**Informations (please complete the following information):**  
 - Browser/App: [e.g. chrome, safari]
 - Bubble Card version: [e.g. 2.0.4]
 - Home Assistant version: [e.g. 2024.6.4]

**Additional context**  

Thank you! 🍻

**Comment by MrBearPresident** [comment] 2024-12-13 19:43
duplicate of #1035

**Closed** 2024-12-13 19:44 UTC
Labels: bug, duplicate
