### ISSUE TITLE
Button - default background color not working (beta9)

### ISSUE THREAD

**Issue by snootched** [Clooos/Bubble-Card#81] opened 2023-09-29 11:16 UTC
After update to b9, all buttons no longer have their background color working on the default settings.
When the entity state is on, the button does not change color.  Revert to b8 and this works again as expected.

Using the new styles functionality for the button in b9 allows me to change the background, however, it's not responding to state ternary operator per the example.

![image](https://github.com/Clooos/Bubble-Card/assets/11273374/405ed31f-7b86-4aaa-a929-d427d20b0b96)

In this example, using styles, the "Front Door Snapshots" button should be 'blue' with entity on.
"Front Door Detect Motion" is showing a default button behavior.  Entity is on, but color isn't changing.

**Comment by Clooos** [comment] 2023-09-29 12:50
This is indeed due to my code rewrite and I forgot to fix this 😅 I will fix this as soon as I can!

**Comment by Clooos** [comment] 2023-09-29 13:16
This is fixed in beta 10 :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.10

**Closed by Clooos** 2023-09-29 13:16 UTC

**Comment by snootched** [comment] 2023-09-29 21:06
Thanks so much for the quick fix!  Works great.
Thanks for your hard work on this project - I'm really enjoying the possibilities it opens up!

**Comment by b-neufeld** [comment] 2024-04-16 03:49
I'm seeing this issue on the 2.0.0-beta 1

**Comment by Clooos** [comment] 2024-04-16 05:24
What do you mean precisely? The button color is correctly changing on my side when the state is on.

**Comment by b-neufeld** [comment] 2024-04-16 12:21
Sorry, I should have been more specific and provide useful info. It's not quite the same issue. 

The issue is I can't change the color of the "on" state from the default orange. Using this style code on a button: 

```
.switch-button {
  background-color: ${state === 'on' ? 'green':'red'} !important;
}
```
 Grid card with embedded bubble cards:
![Screenshot_20240416-061347](https://github.com/Clooos/Bubble-Card/assets/18536548/71b8215f-d8c7-4b65-a945-734abb18a63c)

State is off (first button in list correctly shows specified color):
![Screenshot_20240416-061419](https://github.com/Clooos/Bubble-Card/assets/18536548/5bc552b6-7ffc-4acf-8976-478c2b657de2)

State is on (first button in list is incorrectly orange instead of green):
![Screenshot_20240416-061432](https://github.com/Clooos/Bubble-Card/assets/18536548/6b419f6b-5d6e-4516-962c-e093253b1407)

I'm a new user so could be making a simple mistake. Thanks for your work on this addition, I'm having a blast with it otherwise!
