### ISSUE TITLE
Sub-button Dropdown appearing under other cards

### ISSUE THREAD

**Issue by KlumzyKlein** [Clooos/Bubble-Card#643] opened 2024-07-10 18:13 UTC
Not consistent on what card will be under and what will be on top.

![image](https://github.com/Clooos/Bubble-Card/assets/100074802/63ce55f8-3900-47dc-854b-6a0806158a54)
![image](https://github.com/Clooos/Bubble-Card/assets/100074802/9cc6eaab-1d3f-45ad-b959-2e27cf045672)

**Comment by Clooos** [comment] 2024-07-11 03:44
Duplicate of #624

**Closed by Clooos** 2024-07-11 03:44 UTC
Labels: bug
