### ISSUE TITLE
Media card, no rounded corners after update 2.3.2?

### ISSUE THREAD

**Issue by joasag** [Clooos/Bubble-Card#1038] opened 2024-12-13 07:52 UTC
EDIT: This issue still existed on 2.3.1, but downgrading to 2.3.0 solved it. Some change in 2.3.1 broke the media card for me.

After updating to 2.3.2, my Media card does look weird, the rounded corners are gone?
![bild](https://github.com/user-attachments/assets/f2c05eff-087b-419e-ba1e-ac7277e86054)

This is the YAML:
`type: custom:bubble-card
card_type: media-player
entity: media_player.spotify
hide:
  play_pause_button: false
  volume_button: true
  previous_button: true
  next_button: false
  power_button: true
sub_button:
  - entity: media_player.hela_huset
    name: Hela huset
    show_name: false
    icon: mdi:home-outline
    tap_action:
      action: call-service
      service: script.spela_musik_hela_huset
      target: {}
  - entity: media_player.overallt
    name: Överallt
    show_state: false
    show_name: false
    icon: mdi:home-export-outline
    tap_action:
      action: call-service
      service: script.spela_musik_overallt
      target: {}
  - entity: media_player.sovrum
    name: Sovrum
    icon: mdi:bed-outline
    show_name: false
    tap_action:
      action: call-service
      service: script.spela_musik_sovrum
      target: {}
  - entity: media_player.musik
    icon: mdi:volume-low
    tap_action:
      action: call-service
      service: script.volym_ner
      data:
        entity: media_player.musik
      target: {}
    double_tap_action:
      action: call-service
      service: script.volym_ner_dubbel
      data:
        entity: media_player.musik
      target: {}
    show_background: false
  - name: Volym
    show_name: false
    show_icon: false
    show_background: false
    show_attribute: true
    attribute: volume_level
    tap_action:
      action: none
    entity: media_player.musik
  - entity: media_player.musik
    icon: mdi:volume-plus
    tap_action:
      action: call-service
      service: script.volym_upp
      data:
        entity: media_player.musik
      target: {}
    double_tap_action:
      action: call-service
      service: script.volym_upp_dubbel
      data:
        entity: media_player.musik
      target: {}
    show_background: false
show_icon: true
show_name: true
scrolling_effect: true
force_icon: false
show_attribute: false
layout_options:
  grid_columns: 4
  grid_rows: 1
card_layout: normal
name: Välj källa
icon: mdi:spotify
styles: >-
  ha-card {
    margin-left: 8px;
    margin-right: 8px;
  }  .bubble-icon {
    color: green!important;
  } .bubble-icon-container {
    background: rgba(0, 0, 0, 0.5)!important;
  } .bubble-media-player-container {
    background-color: #2b374e;
  } .bubble-previous-button, .bubble-next-button, .bubble-play-pause-button,
  .bubble-volume-button, .bubble-sub-button-4, .bubble-sub-button-5,
  .bubble-sub-button-6 {
    display: ${hass.states['media_player.spotify'].state === 'idle' ? 'none' : ''} !important;
  } .bubble-sub-button-1, .bubble-sub-button-2, .bubble-sub-button-3,
  .bubble-sub-button-3 {
    display: ${hass.states['media_player.spotify'].state === 'idle' ? '' : 'none'} !important;
    background-color: #424c5e!important;
  } .bubble-sub-button-icon {
    color: #d1d1d1;
  } .bubble-sub-button-4 ha-icon, .bubble-sub-button-5 ha-icon,
  .bubble-sub-button-6 ha-icon {
    color: white!important;
  } .bubble-sub-button-container {
    width: 80px;
  } .bubble-sub-button-4, .bubble-sub-button-5, .bubble-sub-button-6 {
    min-width: 0px!important;
    padding: 0px!important;
  }
tap_action:
  action: call-service
  service: script.stang_av_mediaspelare
  target: {}
double_tap_action:
  action: none
hold_action:
  action: none
cover_background: true
`

**Comment by AlexNikitos** [comment] 2024-12-13 09:49
The same problem with all media cards on version 2.3.1 and 2.3.2

<img width="483" alt="Снимок экрана 2024-12-13 в 12 47 52" src="https://github.com/user-attachments/assets/37eaa5f7-12ec-4c9a-b86f-644b9b5848cb" />

**Comment by MrBearPresident** [comment] 2024-12-13 09:59
Duplicate of #1034

**Closed** 2024-12-13 09:59 UTC
Labels: bug, duplicate
