### ISSUE TITLE
Bad popup alignment (landscape only) on iPad Pro 9.7"

### ISSUE THREAD

**Issue by Arubinu** [Clooos/Bubble-Card#220] opened 2023-12-03 18:02 UTC
Hello, I have recently been using Bubble cards and I find it super interesting.

The problem is that on my iPad, the popup is aligned centered when the tablet is vertical, but is on the left when the tablet is horizontal.

Do you have a solution for this problem?

Buuble Card version: 1.5.3
Model: iPad Pro 9.7"
iPadOS version: 16.7.2
Model Number: MLMV2NF/A

**Comment by Clooos** [comment] 2023-12-03 19:41
Hi and thank you for your feedback. This issue should be fixed in the next release, but I'm unable to reproduce it on my iPad Pro so I can't be sure.

**Comment by Clooos** [comment] 2023-12-18 22:27
This is now fixed in the new v1.6.0 beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1

**Comment by Arubinu** [comment] 2023-12-18 22:53
Thank you for this update which fixes the problem in landscape mode on the iPad.
On the other hand, it is not centered in portrait mode.

On my Android smartphone it's the opposite.
If I can ever help correct this problem, don't hesitate to tell me how :)

**Comment by Clooos** [comment] 2023-12-19 00:18
I was almost sure that it was fixed 😅 Can you send me some screenshots?

**Comment by Arubinu** [comment] 2023-12-19 21:36
Here are the captures with normal use of Bubble Card Popups.

Normally I put the popups in the top horizontal bar (using another tool), because the cards take up space in height, as we can see in the screenshot (the map does not start at the top of the page).
The result is almost the same with this method except that instead of being aligned to the left, the popup is on the right (since I position them to the right of the horizontal bar).

![IMG_0001](https://github.com/Clooos/Bubble-Card/assets/6209760/8303cbe5-d401-411e-b22e-3db693a64be2)
![IMG_0002](https://github.com/Clooos/Bubble-Card/assets/6209760/a1cf85d0-53ea-4062-ae59-134b5a0a5f9f)

**Comment by Arubinu** [comment] 2023-12-19 22:01
This is when I use my method with [](https://github.com/gadgetchnnel/lovelace-header-cards).

![IMG_0003](https://github.com/Clooos/Bubble-Card/assets/6209760/812907f6-bc26-4011-9e4d-41161e2b4805)
![IMG_0004](https://github.com/Clooos/Bubble-Card/assets/6209760/fc3a5585-8602-4a51-9bcf-bfec66ce86f8)

**Comment by Arubinu** [comment] 2023-12-28 02:53
The closing effect is not good, but I was able to rectify the alignment on all my devices with this:
```
#root {
  left: 0 !important;
  right: 0 !important;
  margin: auto !important;
  transform: translateY(-20%) translateX(50%);
}
#root.open-pop-up {
  left: 0 !important;
  right: 0 !important;
  margin: auto !important;
  transform: translateY(-120%) translateX(50%);
}
```

**Comment by barrelltitor** [comment] 2024-03-07 13:24
I have the same issue on an android tablet. The pop up is to the very right side, most of it hidden. Will try the css fix above. If it works, might be worth adding it as an option to the card

**Comment by Clooos** [comment] 2024-04-15 16:05
Hi, this issue should be fixed in the v2 beta, can you confirm this?

Here is the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

**Closed** 2024-04-30 11:27 UTC
Labels: bug
