### ISSUE TITLE
Navigate to another page

### ISSUE THREAD

**Issue by sgtmatty123** [Clooos/Bubble-Card#26] opened 2023-09-01 19:15 UTC
Thankyou for the awesome cards! Dont know if im just being silly but i cant seem to make a button to navigate to another dashboard page. any help would be much appreciated :)

**Comment by Clooos** [comment] 2023-09-03 09:59
Hi. Have you tried this with a regular button (no navigation for now) or with the horizontal buttons stack (this one is working with links)? 

The right path would be /lovelace/your_view_link without ' '.

**Comment by dsellers1** [comment] 2023-09-03 16:27
I can't get the Bubble Button card to navigate either. I set both tap and hold actions. Stock button card does navigate. I took the actions from it and put into the Bubble Button card to ensure I didn't mess it up. 
```yaml
type: custom:bubble-card
card_type: button
entity: input_boolean.tester
tap_action:
  action: navigate
  navigation_path: /dashboard-lab/test
hold_action:
  action: navigate
  navigation_path: /dashboard-lab/test
```
![firefox_NbwcpsztIB](https://github.com/Clooos/Bubble-Card/assets/67642332/3b09e6ac-3bba-46ff-b8a5-ff6ddb1cea60)
I was able to get a horizontal buttons stack button to navigate, but the navigation is a bit weird. Instead of just bringing up the new dashboard view, the page completely reloads/refreshes to the new dashboard view. (This sliding part is clicking the navigation stock button used above; the black part is when I clicked the horizontal stack button.)
![firefox_d8399OoLPr](https://github.com/Clooos/Bubble-Card/assets/67642332/5b4b8cac-814f-4a80-9609-50bd36c81c4e)

**Comment by Clooos** [comment] 2023-09-05 02:17
My bad, this feature is not implemented yet for buttons, you can only navigate with the horizontal buttons stack for now. But I will add that in a future release. All cards possibilities are documented in the documentation.

**Comment by sgtmatty123** [comment] 2023-09-05 19:25
Awesome! thankyou very much

**Comment by Clooos** [comment] 2023-09-10 13:55
Duplicate of https://github.com/Clooos/Bubble-Card/issues/17

**Closed by Clooos** 2023-09-10 13:55 UTC
