### ISSUE TITLE
Crashing the browser consistently

### ISSUE THREAD

**Issue by Nuuki9** [Clooos/Bubble-Card#152] opened 2023-10-31 11:42 UTC
_I commented on Issues #130 but as that's closed and this may be a different cause, I thought a fresh issue was preferable._

I'm seeing consistent stability issues. I just updated to v1.4.2 and after a few tests to nail down the bahaviour, here's what I'm seeing:

1. Create a new dashboard tab.
2. Add a Bubble pop-up card - add a hash value and nothing else. Save.
3. Browse to that dashboard tab.
4. Now, browse to any other dashboard tab.

At that point the browser freezes, and eventually crashes with an "out of memory" warning. Looking at Task Manager, I see my memory usage for the my browser start to rise quickly at step 4, until it crashes.

I've repeated this a bunch of times, using Brave and Edge, and its happening every time.

I'm running HA 2023.10.5 in a container.

**Comment by mrfrag1** [comment] 2023-11-01 10:27
Exactly the same for me.

**Comment by Nuuki9** [comment] 2023-11-02 11:09
I'm getting identical behaviour on 2023.11.0 as I was seeing before, from a Windows browser.

**Comment by mrfrag1** [comment] 2023-11-02 13:35
Even after the update to 2023.11.0 the error still exists.

**Comment by Nazze** [comment] 2023-11-02 20:09
Hey! I recently opened a bug with problems on mobile browser (any like safari, edge and Firefox). In HA companion it was completely refreshing. It got better for a while with version 1.4.2 (or was it even with 1.4.1), why the bug was closed, but I am now seeing it regularly again. I had to revert again to version 1.0.3 to have a stable setup again.

For me it looks like this in HA companion app (Firefox is default browser). Do you have similar issues?

https://github.com/Clooos/Bubble-Card/assets/33813707/d19f46e9-a63c-415a-af44-ba507812632e



PS: I hope that Clooos enjoys the holidays and the beer. Well deserved :-D

**Comment by mrfrag1** [comment] 2023-11-03 06:54
I have exactly the same problems.

When I use the popup card on a blank dashboard, HA becomes increasingly slow. Until it doesn't work at all anymore.

In the HA app on Android and in Edge on Windows.

It's only better in Chrome.

Still GREAT work. The bubble cards are great.

**Comment by florianferry** [comment] 2023-11-03 22:07
> Hey! I recently opened a bug with problems on mobile browser (any like safari, edge and Firefox). In HA companion it was completely refreshing. It got better for a while with version 1.4.2 (or was it even with 1.4.1), why the bug was closed, but I am now seeing it regularly again. I had to revert again to version 1.0.3 to have a stable setup again.
> 
> For me it looks like this in HA companion app (Firefox is default browser). Do you have similar issues?
> 
>  RPReplay_Final1697095427.mov 
> 
> PS: I hope that Clooos enjoys the holidays and the beer. Well deserved :-D

Exactly the same for me !

As I am currently redesigning my dashboard and desperately wanting some kind of sticky footer, I decided to let Bubble aside for the moment while hopefully it’ll get fixed and to try another one. 

So I tried the Mobile First sticky footer, also very nice and also designed by Clooos (you make incredibly beautiful designs !!)

I ran into exactly the same issue ! My dashboard refreshes itself 2 or 3 times and ends up being stuck without anything displayed, exactly like the video previously posted.

Once the sticky footer is removed, everything is working fine.

Maybe the investigation should be oriented toward the compiled JS or something that might be coded the same way for both Mobile First and Bubble Card’s sticky footers instead of performance or memory leaks ?

**Comment by mrfrag1** [comment] 2023-11-04 12:28
With version 1.03 as Nazze said it works without memory problems

**Comment by mrfrag1** [comment] 2023-11-05 10:33
Correction: Even with 1.03 there are memory problems when editing the map in Edge. Only later

**Comment by hellomarb** [comment] 2023-11-07 18:39
There are memory problems in 1.03, but it still works much better on my dashboards.
Chrome Desktop at least is stable, iOS webkit not, but let's wait for a fix for that.

**Comment by Nazze** [comment] 2023-11-08 14:58
> I had my iPhone updated to 17.1.1 and it has not crashed for 2 hours.

Yeah! If I reboot my iPhone, it is stable for a couple of hours. But then the problems appears again.

**Comment by Clooos** [comment] 2023-11-08 15:22
Thanks a lot for all your comments, it helps me a lot! Bubble Card is working great with Chrome (my main browser) but indeed on the other browsers it's pretty terrible, I realize that only now! 😅

I was able to reproduce the issue and that's a good start, this issue is my first priority now.

And I really enjoyed my holidays, thanks!

**Comment by Clooos** [comment] 2023-11-08 16:17
Please tell me that it's working 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v1.4.3

**Comment by hellomarb** [comment] 2023-11-08 16:32
Welcome back ;)
I tested it on iOS 17.1.1: it's better, but I can provoke a reload by switching between 2 crowded views 2-3 times and scroll down and up .
Without debugging it feels like the listeners on the elements causing the memory hog on scroll.

**Comment by Clooos** [comment] 2023-11-08 20:14
And can you all confirm that 1.0.3 was better than this version? I really need to understand what is the root cause of all of this. And thanks again for all all your feedbacks!

**Comment by Nazze** [comment] 2023-11-08 21:35
> Edit: And if you have some console logs to show me when it happens it will help me even more!

I tried to access the console log with developer mode to debug the Firefox on my iPhone from my Mac. But when the issue happens,also the console refreshed, so I am not able to see any errors or so. Really strange. 

Would it make sense that you provide us with a special debug version, with debug outputs or debug logs?

**Comment by mrfrag1** [comment] 2023-11-09 10:58
Excellent !!!

I work with Windows 11 and Edge.
With 1.43I can now edit the bubble cards for 2 hours without it slowing down.

Thank you

**Comment by Clooos** [comment] 2023-11-09 14:22
I'm installing the iOS simulator and I will try to debug this myself first. I really want to be able to reproduce this issue.

**Comment by Clooos** [comment] 2023-11-11 21:22
Hi! I've just released v1.4.4, can you give me your feedbacks? 🤞 
https://github.com/Clooos/Bubble-Card/releases/tag/v1.4.4

**Comment by hellomarb** [comment] 2023-11-12 12:46
I experience the same crash and stuttering while scrolling as before. In an empty "demo" dashboard it works without problems, in a more complex one with picture cards, swiper and tabs it crashes on scroll down/up.

I will check later in the simulator, if it's happening there too.

**Comment by Clooos** [comment] 2023-11-12 17:42
Thanks for your feedbacks! Here is a new beta version, can you please try to follow the instructions to configure it?

https://github.com/Clooos/Bubble-Card/releases/edit/v1.5.0-beta.1

**Comment by hellomarb** [comment] 2023-11-12 18:08
Yes, it looks like it is the one!
The speed increase is really great and until now I wasn't able to break it.
The shadow dom of the popup content is empty until the call, like it should be (kudos for winning that fight!).

Great work, finally Home Assistant feels more like an app and not like a web interface!
I will test it a bit over the next days.

**Comment by Clooos** [comment] 2023-11-12 18:16
Just Yeah !!! 🍻

And now I really hope that it will stay stable after a few days of testing 🤞

**Comment by Clooos** [comment] 2023-11-12 18:19
Just reboot Home Assistant now 🙂

**Comment by hellomarb** [comment] 2023-11-12 18:24
I had to change the path to:
```
  extra_module_url:
    - /hacsfiles/Bubble-Card/bubble-card.js
``` 
It depends on your Home Assistant/HACS setup I think.
You can check if `<YOUR HOMEASSISTANT>/hacsfiles/Bubble-Card/bubble-card.js` is accessible directly in the browser

**Comment by Nazze** [comment] 2023-11-12 18:35
Hi! In the HA companion app, it seems to work (at least for the first tests... but I will test for a while). But on Safari on iOS I still see the refreshes (a least Safari does not say "a problem occured" anymore). But on mobile Safari still not usable. It is okay for me, because I am using the HA companion app, but it seems it is still not fixed 100%..

**Comment by Clooos** [comment] 2023-11-12 18:40
I'm reopening this, that was a miss-click. And it was a typo in the instructions @hellomarb, I've changed it!

Thanks again for all your precious feedbacks!

**Comment by Clooos** [comment] 2023-11-12 19:08
Did you had to clear your browser cache? I'm still not sure if it's optional or not.

**Comment by Clooos** [comment] 2023-11-12 19:13
> Just tweaked the path, delete js from resources page and rebooting now!
> 
> Should this going to work with also picture card with camera entity too?

I haven't tried that yet 🤞

**Comment by Nazze** [comment] 2023-11-12 20:43
Yeah, I can confirm that reload is happening for me, too, on th HA comp. app with the latest beta.

**Comment by Clooos** [comment] 2023-11-13 06:16
Can you show me your console logs when this is happening? Is it possible that any of you as an error related with card-mod? ("You may not getting optimal perf..."), if it the case juste remove card-mod from your resources then clear the cache and see if the error is gone.

**Comment by Clooos** [comment] 2023-11-13 18:53
Yes you can have it of course, just not twice.

**Comment by Clooos** [comment] 2023-11-16 06:52
To everyone here, by any chance do you have one or more cameras inside of your pop-ups? I've just tried without cameras and everything is really smooth (almost no CPU used by Bubble Card). I'm working on a way to disable the cameras when the pop-ups are closed.

**Comment by Nazze** [comment] 2023-11-16 20:17
> To everyone here, by any chance do you have one or more cameras inside of your pop-ups? I've just tried without cameras and everything is really smooth (almost no CPU used by Bubble Card). I'm working on a way to disable the cameras when the pop-ups are closed.

Hi

I don't have cameras in my dashboard. I made an analysis, which cards I use.
Maybe that helps..

I have removed all "unreachable/invalid" entities from my dashboard, but there was no change wrt to stability (tested with 1.5 beta)

Cheers
Denis 

tile | 97
custom:bubble-card | 90
card_separator | 60
vertical-stack | 38
horizontal-stack | 35
custom:mushroom-template-card | 31
card_pop-up | 30
custom:mushroom-chips-card | 16
gauge | 14
back | 12
custom:mushroom-climate-card | 12
custom:auto-entities | 11
light-brightness | 11
cover-open-close | 10
grid | 8
template | 7
conditional | 6
entities | 5
custom:mini-graph-card | 4
custom:mushroom-select-card | 4
sensor | 4
custom:apexcharts-card | 3
custom:mini-media-player | 3
custom:mushroom-number-card | 2
entity | 2
custom:clock-weather-card | 1
custom:mushroom-alarm-control-panel-card | 1
custom:mushroom-light-card | 1
media-control | 1

**Comment by Nazze** [comment] 2023-11-16 21:08
You know that I am still running v1.0.3, @Clooos.
I was using it, because it is the last stable version with HA companion app. 
But I just realized a few things with 1.0.3:
* 1.0.3 is not stable on iOS Safari with 1.0.3 either (crashes right away. )
* I can provoke a crash on edge, if I swipe up.
* I can provoke a hang/blank screen with HA companion app, if I swipe up. 

So it seems the error was always there but triggered only with swipe up. 

See video with 1.0.3 on edge and ha. 
I can retest with any other version. 


https://github.com/Clooos/Bubble-Card/assets/33813707/8e622318-6a8a-4a30-b449-0b384f709734


https://github.com/Clooos/Bubble-Card/assets/33813707/b39bd79e-11bd-47ef-ae71-d7ebdfbf9443

**Comment by Clooos** [comment] 2023-11-17 21:30
This should be THE one : 
https://github.com/Clooos/Bubble-Card/releases/tag/v1.5.0-beta.2

**Comment by Nazze** [comment] 2023-11-18 09:23
I have a similar problem. Changed the code and followed the installation instructions... Reverting now to 1.0.3, otherwise my wife will kill me 😂

<img width="316" alt="grafik" src="https://github.com/Clooos/Bubble-Card/assets/33813707/443bb50e-e3dd-48ea-accd-1dfda723928b">

**Comment by Clooos** [comment] 2023-11-18 10:52
@Nazze indeed the `bubble-pop-up.js` is not included when it is installed with HACS, I thought that it will be downloaded too, my bad! Just add it next to bubble-card.js and it should work.

@willliamchan I really don't understand why you still have this issue. My guess is that some custom cards are in conflict, but I can't be sure without trying your config.

If any of you can create a new dashboard view, then if you can try adding different cards to see what card is slowing it down it would help me a lot! Because on my side this version is the best so far.

And if any of you can share with me its full dashboard YAML (on Pastebin or GitHub), it would help me a lot too!

Thanks in advance!

**Comment by Nazze** [comment] 2023-11-18 12:37
> @Clooos
> 
>As an end-user like me who doesn't know much about the "behind the scenes" stuff would properly want to stick with easy steps only.
> 

Yeah, I would appreciate this, too. I don't want to screw up my system by playing with files...🙈

I have uploaded my dashboard yaml to a private github repo and added you as collaborator, @Clooos . Did you get the invite? Never tried that before...

**Comment by hellomarb** [comment] 2023-11-18 16:33
I can confirm that 1.5.0b2 working now under iOS in a more complex setup.
Only that the card are on first launch are visible until the JS kicks in is not optimal when you have popup cards not at the end of the dashboard, perhaps we can define a initial "out of view" state with translate?

**Comment by Clooos** [comment] 2023-11-18 19:16
Hi again everyone, I've fixed the missing `bubble-pop-up.js` in the new beta. It was indeed an issue with how I configured my repo for HACS. And I'm glad to see that there are no more crashes on your setups!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.5.0-beta.3

@willliamchan thank you for your detailed feedback! I understand that the previous beta was a nightmare to install, but I've just tried beta 3 by installing it from HACS, then I simply added the line in my configuration, restarted Home Assistant, and that's it. I understand that this is an additional step for the end-user, but this is the best way to have pop-ups that really work. I believe that if the user was able to install HACS, they would know how to add a simple line in YAML 🙂 But indeed, I will add something like "Update only card-type:pop-up to use custom:bubble-pop-up.", it will indeed be clearer.

@Nazze you don't risk anything by adding it. This file only impacts your frontend (your browser) and not your Home Assistant installation. I've received your invite and I will take a look at it, thanks!

@hellomarb indeed pop-ups have to be at the end of your view, but since beta 2 this should be fixed. I've never seen any pop-ups content when loading the page. Maybe because I have mostly Bubble Cards, a shopping list, and two cameras in my pop-ups. I will probably have to try a more complex setup to fully debug it. But I will try your suggestion, it's not a bad idea at all!

Thanks everyone, really!

**Comment by Clooos** [comment] 2023-11-18 20:08
Try to clear your cache and/or remove it from your dashboard resources (keep it only in your configuration.yaml), this issue is because you seems to use it twice.

**Comment by Nazze** [comment] 2023-11-18 20:09
@Clooos OK, I managed to install beta3. And the very first test looks quite good. 🥳 No crash on Safari, Edge and Firefox Mobile and on the HA companion app. On Desktop, when I reload, I can see some popup flashing up shortly and disappearing. But this is only during the loading process (you don't have lazy loading or similar mechanisms to speed up the loading?) 

Thanks again for you continuous effort. This is really a great frontend integration. I am happy to be able to create my own dashboard with full flexibility and it is looking really cool!

**Comment by Clooos** [comment] 2023-11-18 20:21
Thanks! I'm so glad you can't imagine! But the pop-up initialization can't be faster now, this update is probably the best that I can get with Bubble Card (for the pop-ups initialization only), if you are still experimenting this issue you can probably try to check if your pop-ups are not too complex. But I can maybe add some kind of "loading screen" that hide everything behind it until everything is initialized, this should be possible for an extra module. I will try something like that.

**Comment by Clooos** [comment] 2023-11-18 20:28
Just add `bubble-pop-up.js` as an extra module in your `configuration.yaml`, `bubble-card.js` need to stay as a resources.

This is not like in the first beta indeed.

**Comment by Nazze** [comment] 2023-11-18 20:43
I am using Mushroom Cards. It has a nice selector, too

https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/select.md

**Comment by Clooos** [comment] 2023-11-18 20:43
> I ask because I got a feeling you are the one who can come up with something fancy and practical!

Flattery tends to work quite well with me! Good job 😂

**Comment by Clooos** [comment] 2023-11-18 20:58
I’m definitely going to do it, I’d just appreciate if you could add a new issue for a feature request so I can finally close this one! ❤️

**Closed** 2023-11-18 20:58 UTC
