### ISSUE TITLE
2.1.0-beta.3 pop up title issue

### ISSUE THREAD

**Issue by pgale** [Clooos/Bubble-Card#647] opened 2024-07-11 19:50 UTC
Obviously something changed in beta 3 as the pop-up titles are now disconnected from the pop-up and showing on the main dashboard. 

https://github.com/Clooos/Bubble-Card/assets/513044/c081bbe5-4663-42db-9a2f-e35fb6432ced

This is a simple test dashboard I setup to test the open/close actions. I can share the code but I guess you should be able to reproduce the issue. Let me know and I can give more info. 

Tested on iOS HA companion app. iPhone and iPad. 

HA Core 2024.7.2

**Comment by Clooos** [comment] 2024-07-12 17:12
What?! 😅 

I haven't seen that one, I will try on a clear dashboard.

**Comment by pgale** [comment] 2024-07-12 17:38
Yeah bit odd

**Comment by Clooos** [comment] 2024-07-13 10:00
Hi again, I've just tried and I'm unable to reproduce this.

But I've seen in your screen record that you have a "Title" text input at the top of your vertical stack, what is it? I don't have this and I have the same HA version, I guess that this is what is causing your issue.

<img width="595" alt="image" src="https://github.com/user-attachments/assets/38a06dc5-b3cc-4e23-bea9-fb4d902572f8">

**Comment by pgale** [comment] 2024-07-13 10:15
Ahhhhh!

It's the title for the vertical stack card!

So I guess that shouldn't be used as it's not handled by the pop-up.

**Comment by Clooos** [comment] 2024-07-13 10:16
Is this a handled by a custom card? I've never seen this.

**Comment by pgale** [comment] 2024-07-13 10:20
https://github.com/user-attachments/assets/275d325c-e62c-45b9-9956-36cf8cd8d71a

**Comment by pgale** [comment] 2024-07-13 10:21
Standard vertical stack - as far as I'm aware.

I do have HACS layout-card installed too - but I didn't think it interferes with this?

**Comment by Clooos** [comment] 2024-07-13 10:23
Nope I can confirm that I don't have this so it should be from that custom card I guess.

I let this open, but for now just don't use these titles 🙂

**Comment by pgale** [comment] 2024-07-13 10:33
Yeah it most be doing something with the vertical stack.

**Comment by Clooos** [comment] 2024-08-21 15:36
Hi, this is issue is now fixed!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.3

**Closed by Clooos** 2024-08-21 15:36 UTC
Labels: bug
