### ISSUE TITLE
Slider doesn’t wait for release after quick re-trigger

### ISSUE THREAD

**Issue by Lansenou** [Clooos/Bubble-Card#852] opened 2024-10-16 19:12 UTC
**Describe the bug**  
The slider sends updates on each value update instead of only when the slider is released.

**To Reproduce**  
1. Drag and release the slider once
2. Quickly after the release hold the slider again
3. When moving the slider my lights will now constantly update

**Expected behavior**  
I’d expect the slider to only update the value whenever the slider is released, just like how it works on the first attempt.

**Informations (please complete the following information):**  
 - OS: iOS (but also windows chrome/firefox)
 - Browser/App: App
 - Bubble Card version: v2.3.0-beta.2
 - Home Assistant version: 2024.10

**Comment by ncodee** [comment] 2024-10-19 22:00
> ScreenRecording_10-16-2024.21-14-06_1.mov 
> I’ve attached a video that shows it happening. (The lights update during the drag)

Did you toggle the option 'Slider live update' to on? 
There was a recent change to how sliders work, in the latest [v2.3.0-beta.2](https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.2).

**Comment by mfrh89** [comment] 2024-10-22 18:55
Not sure if it's the same but I have a similar issue. 

The slider is 100% responsive. When setting a value it slightly jumps to different values before it stops. https://github.com/user-attachments/assets/53e01505-eb88-4917-978d-9c9edf9a6bb1

**Comment by mfrh89** [comment] 2024-10-23 13:37
@Lansenou Thanks for sharing your experience and tips. It happens with grouped lights but also with single lights. The thing is that it only happens with the bubble-card component and not with other sliders. Hence I raised this issue.

**Comment by Heijt771** [comment] 2024-11-05 21:33
I can confirm that I am having the same issue with the slider when set up with a media player

**Software Version:** v2.3.0-beta.4

**Steps to Reproduce:**

1. Assign the slider to a media player entity.
2. Set the `slider_live_update` option to `false`.
3. Drag the volume slider to adjust the volume.

**Current Behavior:**

* When dragging the slider, the media player's volume rapidly fluctuates through all the intermediate values.
* When clicking on a specific point on the slider, the volume jumps directly to that level without transitioning through the intermediate values.

**Expected Behavior:**

* When dragging the slider with `slider_live_update` set to `false`, the volume should only update once when the slider is released, reflecting the final selected value.

**Additional Notes:**

* The issue appears to be related to the interaction between the slider and the media player's volume update mechanism when live updates are disabled.

**Suggested Fix:**

* The slider should respect the `slider_live_update` setting and only send a single volume update command to the media player when the dragging action is completed.

**Comment by areeeee** [comment] 2024-11-08 16:28
I have the same issue at least with some zwave lights.

**Comment by Clooos** [comment] 2024-11-08 18:52
Thank you @Heijt771 for the details! I will fix that in the next beta 👌

**Comment by Heijt771** [comment] 2024-11-08 20:51
**Update:**

The issue seems to have resolved itself. The slider is now working as expected in both the Chrome browser on Windows and the Home Assistant app on Android.

No changes were made to my Home Assistant setup or the slider card configuration since my initial report. The issue seems to have disappeared after three days without any intervention.

**Comment by Clooos** [comment] 2024-11-08 21:54
That was probably a cache issue, it's important to clear all browsers cache after each updates. In your case the cache was probably renewed automatically after three days.

Are the other issues mentioned here fixed as well?

**Comment by Clooos** [comment] 2024-11-09 00:13
I will try to fix that in the next release 👌

**Comment by Clooos** [comment] 2024-11-14 12:48
Hi! I forgot to mention this issue, but this should be fixed now 🙂 

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.5

**Comment by EdanStarfire** [comment] 2024-11-14 14:04
Confirming I was seeing same behaviors - seems to be fixed using v2.3.0-beta.5

**Closed as completed** 2024-11-14 18:14 UTC
Labels: bug
