### ISSUE TITLE
Bubble Card > 1.0.3 constantly refreshes screen and screws up whole setup

### ISSUE THREAD

**Issue by Nazze** [Clooos/Bubble-Card#111] opened 2023-10-14 06:21 UTC
Hi

Every version after 1.0.3 has an issue that it always refreshes the screen and hangs (see video). Happens on Firefox, Edge and Safari on iOS. My setup was not usable anymore, after updating to latest version.
It took me an hour to get to HACS menu and uninstall bubble cards (version 1.0.3 not available anymore)

I really like the idea of this front end module. 
But I will better stick to sub pages and try bubble cards in a couple of months again. 

https://github.com/Clooos/Bubble-Card/assets/33813707/d19f46e9-a63c-415a-af44-ba507812632e

KR
Nazze

**Comment by Clooos** [comment] 2023-10-14 12:26
Hi and thanks for your feedback, this issue should be fixed in 1.2.3, if you still have it installed can you try it and tell me if it fix your issue? Thanks in advance 🙏

**Comment by Nazze** [comment] 2023-10-14 14:04
No Problems on Desktop, but Mobile is still refreshing. :-(

**Comment by Clooos** [comment] 2023-10-14 14:16
There should be some kind of conflict, because I've tested it on Android and iOS without any issues with the companion app and on Chrome, Firefox and Safari on my personal setup with 7 pop-ups. I don't think that there is a major change between 1.0.3 and the new versions, but if it's not too much to ask, can you try to install v1.0.3 by downloading it here on GitHub and by installing it with the "no HACS" method? Because if you don't have this issue anymore on 1.0.3 this will help me a lot understanding why this issue is happening.

**Comment by Nazze** [comment] 2023-10-14 14:25
I will try this evening and get back. KR

**Comment by Nazze** [comment] 2023-10-14 19:28
Hi! I tried the Non-HACS way with both 1.2.3 and 1.0.3.
1.0.3 is fine on both desktop and mobile
1.2.3 is fine on desktop, but has the same issue on mobile.

Is there any debug/logs that might help?

**Comment by Clooos** [comment] 2023-10-14 20:05
Thanks! Your issue seems related with this one, can you try to install 1.1.2 and tell me if it's working for you?

https://github.com/Clooos/Bubble-Card/issues/108

**Comment by Nazze** [comment] 2023-10-14 20:06
You want me to install with HACS or manual?

**Comment by Clooos** [comment] 2023-10-14 20:07
The way you want, it's exactly the same in both ways.

**Comment by Nazze** [comment] 2023-10-14 20:11
Also happening with 1.1.2

**Comment by Nazze** [comment] 2023-10-14 20:16
I don't know, if this related to this. But I see a lot of occurrences of this error in the system log (although the log seems to be related to my desktop, where I don't see any problems):

`Logger: frontend.js.latest.202310050
Source: components/system_log/__init__.py:300
First occurred: 21:23:53 (172 occurrences)
Last logged: 22:12:17

Uncaught error from Firefox 118.0 on Mac OS 10.15 TypeError: document.querySelector(...).shadowRoot.querySelector(...).shadowRoot.querySelector(...) is null set hass (/local/bubble-card.js:1:1465) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:103:8) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:121:27) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:110:13) dispatchEvent (src/common/dom/fire_event.ts:76:7) tag.includes (src/panels/lovelace/create-element/create-element-base.ts:129:14)
Uncaught error from Firefox 118.0 on Mac OS 10.15 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "bubble-card" has already been used with this registry 87659/</window.CustomElementRegistry.prototype.define (src/scoped-custom-element-registry.js:44:14) /local/bubble-card.js:1:36280
Uncaught error from Firefox 118.0 on Mac OS 10.15 TypeError: document.querySelector(...).shadowRoot.querySelector(...).shadowRoot.querySelector(...) is null set hass (/local/bubble-card.js:1:1440) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:103:8) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:121:27) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:110:13) dispatchEvent (src/common/dom/fire_event.ts:76:7) tag.includes (src/panels/lovelace/create-element/create-element-base.ts:129:14)`

**Comment by florianferry** [comment] 2023-10-14 21:42
Hello guys,
I have exactly the same issue... I also tried downgrading to 1.1.2 but the issue remains the same. (i cleared cache and everything)

**Comment by Clooos** [comment] 2023-10-14 22:11
> I don't know, if this related to this. But I see a lot of occurrences of this error in the system log (although the log seems to be related to my desktop, where I don't see any problems):
> 
> `Logger: frontend.js.latest.202310050 Source: components/system_log/**init**.py:300 First occurred: 21:23:53 (172 occurrences) Last logged: 22:12:17
> 
> Uncaught error from Firefox 118.0 on Mac OS 10.15 TypeError: document.querySelector(...).shadowRoot.querySelector(...).shadowRoot.querySelector(...) is null set hass (/local/bubble-card.js:1:1465) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:103:8) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:121:27) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:110:13) dispatchEvent (src/common/dom/fire_event.ts:76:7) tag.includes (src/panels/lovelace/create-element/create-element-base.ts:129:14) Uncaught error from Firefox 118.0 on Mac OS 10.15 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "bubble-card" has already been used with this registry 87659/</window.CustomElementRegistry.prototype.define (src/scoped-custom-element-registry.js:44:14) /local/bubble-card.js:1:36280 Uncaught error from Firefox 118.0 on Mac OS 10.15 TypeError: document.querySelector(...).shadowRoot.querySelector(...).shadowRoot.querySelector(...) is null set hass (/local/bubble-card.js:1:1440) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:103:8) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:121:27) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:110:13) dispatchEvent (src/common/dom/fire_event.ts:76:7) tag.includes (src/panels/lovelace/create-element/create-element-base.ts:129:14)`

Thanks! I hope this will help me find the root cause of this, can you guys also check in the console of your browser if you see any error?

**Comment by Clooos** [comment] 2023-10-14 22:12
> Hello guys, I have exactly the same issue... I also tried downgrading to 1.1.2 but the issue remains the same. (i cleared cache and everything)

And can you try on 1.0.3?

**Comment by Nazze** [comment] 2023-10-18 08:29
If you want, I could install a debug version with further logs, if that helps in debugging.

I tried to implement the dashboard with "subpages", but I really love the bubble cards much more. So I'd love to continue with it. I currently stick with version 1.0.3.  but hope to get this resolved so I can continue updating it.

**Comment by jianyun8023** [comment] 2023-10-18 10:12
I'm having the same problem.

- bubble card 1.2.4
- hass 2023.10.3

**Comment by Nazze** [comment] 2023-10-19 09:20
Hi!
Short update: I just disabled all other frontend modules (clock card, mushroom etc. etc) and had only bubble card 1.2.4 installed. But still it was behaving like this......

**Comment by Clooos** [comment] 2023-10-21 15:29
Can you try with the v1.3.0 and tell me if it's working?

**Comment by Nazze** [comment] 2023-10-21 15:39
Unfortunately 1.3.0. does not work for me. And strangely I had the "nested pop-up" issue on Deskop again.

**Comment by Clooos** [comment] 2023-10-21 15:44
For the nested pop-up issue just add `back_open: true` to every pop-ups. And for your second issue I guess that there is some kind of conflict with an other component, but I'm really not sure of why it's happening.

Have you tried on a blank and new dashboard view? Because it should work like a charm.

**Comment by Clooos** [comment] 2023-10-21 15:56
Can you try with v1.3.1, I've fixed something from your logs.

**Comment by Nazze** [comment] 2023-10-21 15:57
Will give it a try tomorrow on a blank dashboard. But as said, I had disabled all front end modules and still causes problems. 
My dashboard is really huge. Don’t know if simply the size is causing problems.

**Comment by Nazze** [comment] 2023-10-21 15:58
> Can you try with v1.3.1, I've fixed something from your logs.

I will try later today or tomorrow. Sorry, just need to leave home now.

**Comment by Nazze** [comment] 2023-10-22 11:18
Hi! I tried on a very basic dashboard. Only one button and a popup. Mobile was working (desktop somehow the pop-up did not open, but I would ignore it for now). Will later try adding popup by popup and find out, which section might cause a conflict.

**Comment by Nazze** [comment] 2023-10-22 15:10
Hi! So I started with a blank dashboard and added stack by stack to the raw yaml and tested.
I can't really tell, when exactly it is happening. But I believe it is simply the size of it. With every stack I add, the dashboard takes longer to load and at one point in time it is getting into this infite refresh..
Could it be simply the size of the dashboard with 2250 lines (when I look at the raw yaml)?

I added "back_open: true" to every pop-up, but nested pop-ups are not working on Desktop.

**Comment by Nazze** [comment] 2023-10-28 12:27
Hey @Clooos ! I followed this thread here:
https://github.com/Clooos/Bubble-Card/issues/125

It seems that this also fixed my issue. It required a reboot of my iPhone (although I cleared cache in the companion app, but a reboot was necessary).

Thank you so much for your effort. I thought, you deserved a couple of beers ;-) Cheers!

**Closed** 2023-10-28 14:09 UTC
