### ISSUE TITLE
Feature Request: Single action function for bubble button

### ISSUE THREAD

**Issue by benepixx** [Clooos/Bubble-Card#33] opened 2023-09-05 08:39 UTC
Awesome project! I was adding buttons in to trigger scenes and noticed they don't work. The service called for the bubble button "generic toggle" doesn't work for scenes. Its a HA limitation. Could we have a way of selecting the service called by the button or a single action function which allows to send one-shot commands like scenes etc?
![IMG_1497](https://github.com/Clooos/Bubble-Card/assets/53353052/4051912a-d6c8-4167-91dd-eea972742fdf)

**Comment by Clooos** [comment] 2023-09-05 10:57
Thanks for the feedback, I will add that indeed. For now you can create an input_boolean that is a trigger for an automation that run you script, this is how I trigger them.

**Comment by Clooos** [comment] 2023-09-10 13:56
Duplicate of https://github.com/Clooos/Bubble-Card/issues/17

**Closed by Clooos** 2023-09-10 13:56 UTC
