### ISSUE TITLE
Add support for water_heater in Climate button.

### ISSUE THREAD

**Issue by MJLHThomassen** [Clooos/Bubble-Card#1024] opened 2024-12-11 08:56 UTC
When using the climate button, i only see "climate" entities. However, "water_heater" entities work in exactly the same way. 
I know the default "thermostat" home assistant card also does not support "water_heater" entities, but it would be nice if bubble card could add this.

Since, when i navigate to the entity screen for a water heater, i get the same circular slider and mode selector as for climate entities, see below.

water_heater: (entity id water_heater.altherma)
![image](https://github.com/user-attachments/assets/dcb1ce30-24da-4773-b862-d90d2fe51fdf)

climate: (entity id climate.altherma_room_temperature)
![image](https://github.com/user-attachments/assets/31738430-f8ed-4853-9a80-208cb41eb5f4)

The water heater is for my tap water, the climate is for my floor heating.

**Comment by MrBearPresident** [comment] 2024-12-11 10:01
Duplicate of #955

**Comment by MrBearPresident** [comment] 2024-12-11 10:02
Please continue conversation over there.

**Closed** 2024-12-11 10:02 UTC
Labels: duplicate, enhancement
