### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by ddanielww** [Clooos/Bubble-Card#856] opened 2024-10-18 17:34 UTC
I have an issue when I open a bubble card it breaks the Navigation on home assistant.

For example if I open a bubble card and then go to settings > devices > click device, I can’t go back to the list of devices.

If refresh the page or reset the cache it works until I open a bubble card again.

**Comment by ddanielww** [comment] 2024-10-18 18:53
Uploading Bubble Bug.mp4…

As you can see before I open the bubble card I go to to devices, click a device and go back.

Once I open a bubble card Navigation stop working.

Effects all areas like automations etc.

**Comment by ddanielww** [comment] 2024-10-18 18:54
https://github.com/user-attachments/assets/181c557a-83ed-4625-8aa5-80aaf54ecd91

**Comment by Clooos** [comment] 2024-10-18 19:25
Hi, I've just tried and I'm unable to reproduce this issue on my setup, do you have some other custom cards?

**Comment by ddanielww** [comment] 2024-10-18 19:27
Nope, just the bubble card and the problem only appears after popping up a bubble card :(

**Comment by ddanielww** [comment] 2024-10-18 19:35
https://github.com/user-attachments/assets/d462cb6c-e42e-4ebe-a9dc-5f3f0e77280d

Even on a basic setup with a new dashboard it breaks it.

**Comment by ddanielww** [comment] 2024-10-18 19:39
Correct I thought it was an issue with the home assistant core.

Drove me mad ..... after disabling stuff I found the issue was the bubble card.

Reported by others using the bubble card here as well

 https://github.com/home-assistant/frontend/issues/17820#issuecomment-2422997801

**Comment by ddanielww** [comment] 2024-10-18 19:46
Tried v2.2.4 and the latest beta2 but opening a bubble card breaks navigation.

Remove bubble card and use standard items and it works.

Refreshing the browser fixes the issue or closing the app and re-opening but bubble card appears to be causing this issue.

**Comment by Clooos** [comment] 2024-10-18 19:47
Thank you, I will take a look at this then. I hope that I will be able to reproduce it.

**Comment by ddanielww** [comment] 2024-10-18 20:02
Check the console nothing useful 

[Deprecation] -ms-high-constrast is in the process of being deprecated
https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/

Are you saying your home assistant navigation works after opening a bubble card ?

**Comment by Clooos** [comment] 2024-10-18 21:08
Yes, I just tried again and no issue at all.

**Comment by ddanielww** [comment] 2024-10-18 21:21
Strange , only breaks when I use the bubble card on my install. Gonna try and fresh instance of home assistant in a VM and see if can replicate it with the bubble card there.

**Comment by Clooos** [comment] 2024-10-18 21:24
Thank you! But this is weird that you seems to not be the only one.

**Comment by ddanielww** [comment] 2024-10-18 22:45
https://github.com/user-attachments/assets/1ac37045-0c2c-45b0-bd41-8161d1fc1853

Now sure how you can not replicate, same issue on fresh install :(

**Comment by Clooos** [comment] 2024-10-18 23:31
I'm using a more recent version than what is on GitHub, but I don't remember if I changed something that could have fixed this.

Thank you again for your test, we will see in the next beta 🤞

**Comment by ddanielww** [comment] 2024-10-19 08:26
When will this be available for testing please.

I really like this card but this bug drives me crazy.

**Comment by Clooos** [comment] 2024-10-19 09:28
I'm doing my best, I've made some progress, so it shouldn't be too long, in less than a week I hope.

**Comment by Clooos** [comment] 2024-10-19 19:27
I've tried again on multiple browsers (desktop and mobile) and I can confirm that this is fixed on my current build.

**Comment by ddanielww** [comment] 2024-10-19 19:29
Any chance we can test this to confirm ?

love your card it’s the best but this bug spoils it for me haha

**Comment by Clooos** [comment] 2024-10-19 19:38
Here it is, you will need to remove it from HACS first then install it with the ["Without HACS" method](https://github.com/Clooos/Bubble-Card/?tab=readme-ov-file#installation).

The media player card has no rounded border for now, that's the only issue in this build.

All my fingers are crossed 🤞 

[bubble-card.js.zip](https://github.com/user-attachments/files/17447064/bubble-card.js.zip)

**Comment by ddanielww** [comment] 2024-10-19 19:48
![Capture -2024-10-19](https://github.com/user-attachments/assets/e5473464-2220-416d-9c70-52f0c91d557a)

Replaced the JS file, but I still have the same issue :(

**Comment by ddanielww** [comment] 2024-10-19 19:49
![Capture -2024-10-19](https://github.com/user-attachments/assets/87c79317-e965-498b-985f-49ed0f46c9ff)

**Comment by ddanielww** [comment] 2024-10-19 19:50
Also tested on my fresh install and same issue there :(

**Comment by ddanielww** [comment] 2024-10-19 19:56
Sorry I did not remove it from hacs, i replaced the JS file and rebooted.

Removing and manually installing gets rid of the issue, thank you so much =)

**Comment by ddanielww** [comment] 2024-10-19 20:03
![Capture -2024-10-19](https://github.com/user-attachments/assets/ac262193-c7df-4d4f-9764-7530783359f2)

Bug in the new version, the name does not display.

Reset cache but no difference, I can live with this though for now, at least I can Navigate =)

**Comment by Clooos** [comment] 2024-10-19 20:19
Yeah! You scared me! 😅

**Comment by ddanielww** [comment] 2024-10-19 20:21
So nice to have working navigation :), appreciate the quick turn around. Have a lovely weekends and thanks again :)

**Comment by Clooos** [comment] 2024-10-19 20:26
You're welcome! Have a nice weekend as well!

**Comment by ronbruins** [comment] 2024-10-20 14:39
I have a similar issue but then with automations. When clicking the back arrow it doesn't work, I have to click settings -> automations -> automation again. Is this related (and as such fixed)? I saw bubble card mentioned in an issue in the HA core for this behavior.

**Comment by ddanielww** [comment] 2024-10-20 15:14
Same issue it affected all areas of the system after selecting a bubble card.

The developer haze kindly fixed this by providing a new JS file above, you will need to manually install.

Or you can wait for it to get released to hacs.

**Comment by ronbruins** [comment] 2024-10-20 15:17
I'll give it a try with the beta. Thanks

**Comment by ddanielww** [comment] 2024-10-22 21:11
This problem still appears in beta 3, however, it didn’t appear when manually installing using the file you provided ?

**Comment by Clooos** [comment] 2024-10-22 21:17
What?? Could you try to install the new beta manually? Have you also checked if the right version is showing in the editor? I haven't changed anything that might have broken this again.

**Comment by ddanielww** [comment] 2024-10-22 21:22
Took the file out of the community folder (Where hacs installs it).

Uninstalled from hacs and deleted community folder.

Placecd the file in www folder.

Added resource and it works.

Could it be the be the haccs is picking the information up or something?

**Comment by ddanielww** [comment] 2024-10-22 21:34
installing the latest beta through hacs does not work.

If re-install using the general release it all appears correct (apart from the back bug).

![Capture -2024-10-22](https://github.com/user-attachments/assets/3dbb87d7-9822-4cf8-a3a6-7a87edc82727)

**Comment by ddanielww** [comment] 2024-10-22 22:00
Seems to be an issue the the Hacs installation but I can’t work out why.

If I install latest beta it does not render the bubble cards as shown above.

I can get it to work by altering the resource and removing the hacs id ( the auto generated entry by hacs) but then the back button does not work.

If I download the file from the hacs folder , delete the resource, uninstall and remove any files and manually upload the same file and add resource manually it works.

The back issue seems to be related to installing through hacs. New beta does not install correctly.


Gonna leave mine manually configured because that works nicely :)

**Comment by Clooos** [comment] 2024-10-22 22:02
I really don't understand why this is happening, this doesn't make any sense to me 😅

But I will try to install it though HACS to see if I can reproduce this issue.

**Comment by Clooos** [comment] 2024-12-10 19:15
This issue was from Home Assistant, and should be now finally fixed in the next HA release!

https://github.com/home-assistant/frontend/issues/17820#issuecomment-2531304967

I'm closing this 🙂

**Closed by Clooos** 2024-12-10 19:15 UTC
Labels: bug
