### ISSUE TITLE
Bubble Card Makes Lovelace Very Slow

### ISSUE THREAD

**Issue by JoeyGE0** [Clooos/Bubble-Card#840] opened 2024-10-07 04:53 UTC
**Describe the bug**  
Very slow lovelace with any bubble cards added. more bubble cards= more errors and slowdowns.

prevents. edit button from working or very slow response. other buttons work fine

**To Reproduce**  
add bubble cards

**Expected behavior**  
to operate smoothly, error free.

**Screenshots**  
![IMG_6088](https://github.com/user-attachments/assets/2374b730-0ba0-40e3-9e42-46c3450109ab)

**Informations (please complete the following information):**  
 - OS: [iOS, android, macos, windows]
 - Browser/App: [chrome, safari, home assistant app]
 - Bubble Card version: [2.3.0 beta.2] (went to this as it i was having issues with previous versions)
 - Home Assistant version: [e.g. 2024.10.1]

**Additional context**  
to get my main dashboard working normally all bubble cards had to be removed. (even plain separators)

help would be great!

**Comment by ironboy1** [comment] 2024-10-07 18:27
Same here

**Comment by Clooos** [comment] 2024-10-07 20:13
Thank you for the feedback! I still don't understand why some users get that error and some don't, but I will find a way to fix that.

**Comment by JoeyGE0** [comment] 2024-10-09 02:58
thanks so much Clooos!

**Comment by jerome6994** [comment] 2024-10-15 21:14
Good evening

then the problem is still present despite version v2.3.0-beta.2

I restarted HA but didn't clear the chrome cache.

I even have difficulty saving following modifications finally when I open a new tab it is saved but the window does not close and runs in a loop

**Comment by Clooos** [comment] 2024-10-16 03:19
Hi! Can you take a look at your browser console to see if there is any error?

**Comment by danielholm** [comment] 2024-10-16 06:53
Same here. I'll try to find some logs that could help. Running latest beta.

**Comment by Clooos** [comment] 2024-10-26 18:57
Hi! Just an update to say that this issue will be fixed in the next beta, I really hope that it will not happens anymore after that 🤞

**Comment by ironboy1** [comment] 2024-10-26 20:37
Looking forward and thanks for the great support! 😊

**Comment by Pheerink** [comment] 2024-11-18 11:44
I'm having the same problem! Pressing a button on a pop-up menu is very slow. Also the non-bubble cards (e.g. light) will slow down. I tried the latest beta but that doesn't make any difference.  Removing the bubble-cards will speed the other cards up again.

**Comment by Clooos** [comment] 2024-11-18 11:48
Hi @Pheerink, a lot of users said that the newest betas were improving performance a lot, in your case can you take a look at your browser console to see if there is any error?

**Comment by KipK** [comment] 2024-11-18 17:24
Hi, 

I've tested latest beta 2.3.0 beta 7 and it seems its solved. 
Pop-up is smoother, and no error in dev console. 👍

**Comment by Clooos** [comment] 2024-11-19 17:53
Thank you for the feedback! I will close this then 🎉

**Closed by Clooos** 2024-11-19 17:53 UTC
Labels: bug
