### ISSUE TITLE
Dropdown menus out of place?

### ISSUE THREAD

**Issue by jockebq** [Clooos/Bubble-Card#469] opened 2024-04-19 08:29 UTC
I have some weird behaviour with [lovelace-xiaomi-vacuum-map-card 1](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card) in a Bubble Card.
On desktop when clicking the dropdown:

![](https://community-assets.home-assistant.io/original/4X/4/f/d/4fd4c2732b28b7ee4857973e62f9af1358889275.jpeg)
On mobile when clicking the dropdown:

![](https://community-assets.home-assistant.io/original/4X/b/7/f/b7f1a2ae4eac0955a46fbde87a855633169f386c.jpeg)

And if I click the dropdown on a normal card (not bubble card), works with mobile and desktop:

![](https://community-assets.home-assistant.io/original/4X/1/0/c/10cb7975aaddcbac84464de7a159178b2b038e7b.jpeg)

This is on 1.7.3, updated to 2.0 Beta 2 to try if it was fixed. Now I cannot even see the dropdown at all?

**Comment by Clooos** [comment] 2024-04-19 10:26
This issue should be fixed in the next release, thank you for the feedback!

**Comment by Clooos** [comment] 2024-04-25 08:49
This issue is now fixed in the new beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3

**Comment by Clooos** [comment] 2024-04-25 11:24
Do you have modified the style of this card by any chance? And also was it working with the previous 1.7.3 release?

**Comment by jockebq** [comment] 2024-04-25 11:26
Some modifications, but I tried with a default vacuum card and experienced the same issue. It did not work with 1.7.3 or any Beta version.

**Comment by Clooos** [comment] 2024-04-25 11:27
Thank you for the details, I will take a closer look at this.

**Comment by Clooos** [comment] 2024-04-25 11:58
I've just tried and indeed this issue is from that card, there is nothing that I can do on that. 

But it would be great if you could open an issue on its GitHub 🙂

**Comment by Clooos** [comment] 2024-04-25 12:11
Like he said:

"I suspect that Bubble Card modifies some properties that are used by the dropdown to determine its position… It is a problematic thing to fix"

This is indeed because you are putting it in a pop-up but there is nothing that I can do about that, this issue is still about how this card is positioning that dropdown. The pop-ups are not modifying the CSS of the cards inside of it.

**Comment by joq3** [comment] 2024-09-20 07:43
I have done some more testing, and it seems to be only happening on a mobile browser, or if you go to developer mode and select a phone on your regular browser. That way the drop downs are always misplaced when inside a Bubble card (does not happen outside Bubble cards).
Using it on a desktop browser it works fine in Bubble cards however.

So there seems to be an issue with Bubble card and specifically in mobile mode.

**Comment by joq3** [comment] 2024-09-20 07:52
Found the issue!
I have all my popups set to "Optional - Top margin on mobile" to 6% to not go all the way up.
This is what causes the issue with the select not being correctly displayed.

Same issue happens if I change from % to vh. Any idea on how to solve this?
Right now it only works properly with -56px

**Comment by Clooos** [comment] 2024-09-20 07:57
Hi! Have you tried to use `calc(100vh - 400px)`? Just replace 400px with the size you want for your pop-up, this should works.

**Comment by joq3** [comment] 2024-09-20 08:06
> Hi! Have you tried to use `calc(100vh - 400px)`? Just replace 400px with the size you want for your pop-up, this should works.

Tried it, with the same result as the other settings. I actually was wrong about it working fine on desktop.
On desktop it only works properly inside the editor preview. But when I view it on my dashboard I cannot even see the select items after I click select:
![bild](https://github.com/user-attachments/assets/63d504ff-56e2-409b-8b21-2681a2a3d8f4)

This is how it looks on mobile with -56px which is how it should look.
![bild](https://github.com/user-attachments/assets/5bc10209-f33e-4ee3-a35f-6e1c30f74421)

**Comment by joq3** [comment] 2024-09-20 08:08
This is my current settings:
![bild](https://github.com/user-attachments/assets/c5667ebf-d7a5-4215-9bee-16009f76acc9)

Setting top margin on desktop to 0px (or empty) does not even show the bubble card? I have to set it to something else.

**Comment by Clooos** [comment] 2024-09-20 08:20
I've tried and I can reproduce your issue, I will try to fix that for the next release 🤞

**Comment by joq3** [comment] 2024-09-20 08:22
> I've tried and I can reproduce your issue, I will try to fix that for the next release 🤞

Fantastic! On both mobile and desktop?

**Comment by Clooos** [comment] 2024-09-20 08:23
I tried only on desktop for now, I will try both.

**Comment by Clooos** [comment] 2024-09-20 08:37
For some reason it is working for me by adding:

```
bg_blur: none
```

Can you confirm this?

**Comment by joq3** [comment] 2024-09-20 08:44
> For some reason it is working for me by adding:
> 
> ```
> bg_blur: none
> ```
> 
> Can you confirm this?

Yes, that solves the issue!
Is there any workaround I can do to fix the issue while keeping the bg_blur on?

**Comment by Clooos** [comment] 2024-09-20 08:45
I'm on it, I just wanted to be sure 👌

**Comment by Clooos** [comment] 2024-09-25 12:01
I've finally fixed it, just wait for the next beta release! 🥳

**Comment by joq3** [comment] 2024-09-25 12:25
Great! Thank you!

**Comment by Clooos** [comment] 2024-10-04 15:29
Hi, the new beta is here, I hope that it is working now 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.2

**Closed** 2024-12-03 18:09 UTC
Labels: bug
